header:
  license:
    content: |
      SPDX-License-Identifier: Apache-2.0

  paths:
    - 'src/*'

  paths-ignore:
    - 'target'
    - '**/*.toml'
    - '**/*.lock'
    - 'CHANGELOG'
    - 'LICENSE'
    - '.gitignore'
    - '**/*.txt'

  comment: on-failure
